export const ACCESS_JWT = 'ACCESS_JWT';
export const REFRESH_JWT = 'REFRESH_JWT';

export const ACCESS_TOKEN_TTL_SECONDS = 60;
export const ACCESS_TOKEN_EXPIRATION_TIME = `${ACCESS_TOKEN_TTL_SECONDS}s`;

export const REFRESH_TOKEN_TTL_SECONDS = 604_800; // 7 days
export const REFRESH_TOKEN_TTL_MS = REFRESH_TOKEN_TTL_SECONDS * 1000;
export const REFRESH_TOKEN_EXPIRATION_TIME = `${REFRESH_TOKEN_TTL_SECONDS}s`;
